sudo_password '';

sub get_svn_version {
  my $version;
  open my $pipe, '-|', 'svn --version'
    or die "cannot exec svn --version: $!";
  while (<$pipe>) {
    if (/version (\S+)/) {
      $version = $1;
    }
    last;
  }
  close $pipe;
  return $version;
}

sub exec_sql {
  my $sql = shift;
  open my $fh, '|-', 'mysql -uroot' or die $!;
  print $fh $sql;
  close $fh;
}

task 'check_svn17', sub {
  print 'version=', get_svn_version();
};

task 'install_svn17', sub {
  sudo '
yum install -y apr-devel apr-util-devel httpd-devel neon-devel openssl-devel sqlite-devel perl-ExtUtils-Embed
cd /usr/local/src
curl -LO http://ftp.riken.jp/net/apache/subversion/subversion-1.7.3.tar.bz2
tar xf subversion-1.7.3.tar.bz2
cd subversion-1.7.3
./configure --with-apxs
make
make install
';
};

task 'install_mysql', sub {
  sudo '
yum install -y mysql-server
/etc/init.d/mysqld start
/sbin/chkconfig mysqld on
';
  exec_sql <<'EOF';
-- remove anonymous users
DELETE FROM mysql.user WHERE User='';
-- Disallow root login remotely
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
-- Remove test database and access to it
DROP DATABASE test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
-- Reload privilege tables now
FLUSH PRIVILEGES;
EOF
};

task 'install_redmine133', sub {
  sudo '
yum install -y mysql-devel
gem install rack -v=1.1.1
gem install rake -v=0.8.7
gem install i18n -v=0.4.2
gem install mysql
gem install rails -v=2.3.14
gem install coderay -v=1.0.4
gem install rw_fastercsv -v=1.5.7
cd /usr/local/src
curl -LO http://rubyforge.org/frs/download.php/76013/redmine-1.3.3.tar.gz
tar xf redmine-1.3.3.tar.gz
cd redmine-1.3.3
cp config/database.yml.example config/database.yml
';
  exec_sql <<'EOF';
create database redmine character set utf8;
grant all privileges on redmine.* to 'root'@'localhost';
EOF
  sudo '
cd /usr/local/src/redmine-1.3.3
rake generate_session_store
rake db:migrate RAILS_ENV=production
';
};

task 'install_passenger', sub {
  sudo '
gem install passenger -v=3.0.11
passenger-install-apache2-module -a
';
};
